jobs:
  build:
    name: Java ${{ matrix.jdk }} / ${{ matrix.os }} ${{ matrix.args }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: true
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      if: ${{ !contains(matrix.os, 'windows') }}
      name: Build with mvnw (linux/mac)
      run: ./mvnw ${{matrix.args}} -Dspotless.check.skip --batch-mode -no-transfer-progress
        package verify jib:buildTar --file pom.xml
    - continue-on-error: true
      if: ${{ contains(matrix.os, 'windows') }}
      name: Build with mvnw.cmd (windows)
      run: mvnw.cmd ${{matrix.args}} -Dspotless.check.skip --batch-mode -no-transfer-progress
        package verify jib:buildTar --file pom.xml
      shell: cmd
    strategy:
      fail-fast: false
      matrix:
        include:
        - args: -DargLine='-Duser.language=fr -Duser.country=FR'
          jdk: 21
          os: ubuntu-latest
        - args: ''
          jdk: 21
          os: ubuntu-latest
        jdk:
        - 21
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    timeout-minutes: 15
  examples:
    continue-on-error: true
    name: Example project
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: true
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Build and test
      run: mvn --batch-mode -no-transfer-progress package --file standalone.pom.xml
      working-directory: planetiler-examples
    - continue-on-error: true
      name: Find jar
      run: mv target/*with-deps.jar ./run.jar
      working-directory: planetiler-examples
    - continue-on-error: true
      name: Run
      run: java -jar run.jar --osm-path=../planetiler-core/src/test/resources/monaco-latest.osm.pbf
        --output=data/out.mbtiles
      working-directory: planetiler-examples
    - continue-on-error: true
      name: Verify
      run: java -cp run.jar com.onthegomap.planetiler.mbtiles.Verify data/out.mbtiles
      working-directory: planetiler-examples
    timeout-minutes: 15
  lint:
    name: Check formatting
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: true
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Ensure code formatted with mvn spotless:apply
      run: ./mvnw -DskipTests --batch-mode -no-transfer-progress spotless:check
    timeout-minutes: 15
  quickstart:
    name: Quickstart script
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: true
    - continue-on-error: true
      name: Cache data/sources
      uses: ./.github/cache-sources-action
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: quickstart.sh --build
      run: rm -rf data/output.mbtiles data/tmp && ./quickstart.sh monaco --build &&
        ./scripts/check-monaco.sh data/output.mbtiles
    - continue-on-error: true
      name: quickstart.sh --jar
      run: rm -rf data/output.mbtiles data/tmp && ./quickstart.sh monaco --jar &&
        ./scripts/check-monaco.sh data/output.mbtiles
    - continue-on-error: true
      name: quickstart.sh --docker
      run: rm -rf data/output.mbtiles data/tmp && ./quickstart.sh monaco --docker
        && ./scripts/check-monaco.sh data/output.mbtiles
    timeout-minutes: 15
  run:
    name: Build / Run
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: true
    - continue-on-error: true
      name: Cache data/sources
      uses: ./.github/cache-sources-action
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Build this branch
      run: ./mvnw -DskipTests -Dimage.version=CI_ONLY --batch-mode -no-transfer-progress
        package jib:dockerBuild --file pom.xml
    - continue-on-error: true
      name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: planetiler-build
        path: planetiler-dist/target/*with-deps.jar
    - continue-on-error: true
      name: Download data (java)
      run: java -jar planetiler-dist/target/*with-deps.jar --only-download --area=monaco
    - continue-on-error: true
      name: Download wikidata (java)
      run: java -jar planetiler-dist/target/*with-deps.jar --only-fetch-wikidata --area=monaco
    - continue-on-error: true
      env:
        SKIP_EXAMPLE_PROJECT: true
      name: Verify build
      run: ./scripts/test-release.sh CI_ONLY
    timeout-minutes: 15
name: CI
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
