env:
  AREA: rhode island
  BOUNDS_ARG: --bounds=-74.07,21.34,-17.84,43.55
  RAM: 4g
jobs:
  performance:
    continue-on-error: true
    name: Performance Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ github.token }}
    - continue-on-error: true
      name: Checkout branch
      uses: actions/checkout@v4
      with:
        path: branch
        submodules: true
    - continue-on-error: true
      name: Checkout base
      uses: actions/checkout@v4
      with:
        path: base
        ref: ${{ github.event.pull_request.base.sha }}
        submodules: true
    - continue-on-error: true
      name: Cache data/sources
      uses: ./branch/.github/cache-sources-action
      with:
        basedir: branch
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: '14'
    - continue-on-error: true
      run: npm install -g strip-ansi-cli@3.0.2
    - continue-on-error: true
      name: Build branch
      run: ./scripts/build.sh
      working-directory: branch
    - continue-on-error: true
      name: Build base
      run: ./scripts/build.sh
      working-directory: base
    - continue-on-error: true
      name: Download data
      run: 'set -eo pipefail

        cp base/planetiler-dist/target/*with-deps.jar run.jar && java -jar run.jar
        --only-download --area="${{ env.AREA }}"

        cp branch/planetiler-dist/target/*with-deps.jar run.jar && java -jar run.jar
        --only-download --area="${{ env.AREA }}"

        '
    - continue-on-error: true
      name: Store build info
      run: 'mkdir build-info

        echo "${{ github.event.pull_request.base.sha }}" > build-info/base_sha

        echo "${{ github.sha }}" > build-info/branch_sha

        echo "${{ github.event.number }}" > build-info/pull_request_number

        '
    - continue-on-error: true
      name: Run branch
      run: 'rm -rf data/out.mbtiles data/tmp

        cp branch/planetiler-dist/target/*with-deps.jar run.jar

        java -Xms${{ env.RAM }} -Xmx${{ env.RAM }} -jar run.jar --area="${{ env.AREA
        }}" "${{ env.BOUNDS_ARG }}" --output=data/out.mbtiles --keep-unzipped 2>&1
        | tee log

        ls -alh run.jar | tee -a log

        cat log | strip-ansi > build-info/branchlogs.txt

        '
    - continue-on-error: true
      name: Run base
      run: 'rm -rf data/out.mbtiles data/tmp

        cp base/planetiler-dist/target/*with-deps.jar run.jar

        java -Xms${{ env.RAM }} -Xmx${{ env.RAM }} -jar run.jar --area="${{ env.AREA
        }}" "${{ env.BOUNDS_ARG }}" --output=data/out.mbtiles --keep-unzipped 2>&1
        | tee log

        ls -alh run.jar | tee -a log

        cat log | strip-ansi > build-info/baselogs.txt

        '
    - continue-on-error: true
      name: Upload build-info
      uses: actions/upload-artifact@v4
      with:
        name: build-info
        path: ./build-info
    timeout-minutes: 20
name: Performance
on:
  repository_dispatch:
    types: trigger-ga___performance.yml
