jobs:
  snapshot:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: true
    - continue-on-error: true
      name: Cache data/sources
      uses: ./.github/cache-sources-action
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      run: ./scripts/build-release.sh
    - continue-on-error: true
      run: ./scripts/test-release.sh
    - continue-on-error: true
      run: sha256sum planetiler-dist/target/*with-deps.jar
    - continue-on-error: true
      run: md5sum planetiler-dist/target/*with-deps.jar
    - continue-on-error: true
      name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: planetiler-build
        path: planetiler-dist/target/*with-deps.jar
    - continue-on-error: true
      name: Install GPG Private Key
      run: 'echo -n "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | base64 --decode | gpg
        --batch --import

        '
    - continue-on-error: true
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_TAGS: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.image_tags
          || 'latest,snapshot' }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      run: ./scripts/push-release.sh
    timeout-minutes: 20
name: Publish a Snapshot
on:
  repository_dispatch:
    types: trigger-ga___snapshot.yml
