jobs:
  updatepr:
    continue-on-error: true
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion
      == 'success' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: haya14busa/action-workflow_run-status@v1
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: true
    - continue-on-error: true
      name: Download branch build info
      uses: dawidd6/action-download-artifact@v3
      with:
        name: build-info
        path: build-info
        run_id: ${{ github.event.workflow_run.id }}
        workflow: ${{ github.event.workflow_run.workflow_id }}
    - continue-on-error: true
      id: build_info
      name: Get build info
      run: echo "::set-output name=pr_number::$(cat build-info/pull_request_number)"
    - continue-on-error: true
      name: Build comment-body
      run: "cat build-info/branchlogs.txt | sed -n '/^.*Tile stats/,$p' > branchsummary.txt\n\
        cat build-info/branchlogs.txt | sed -n '/^.*Exception in thread/,$p' >> branchsummary.txt\n\
        cat build-info/baselogs.txt | sed -n '/^.*Tile stats:/,$p' > basesummary.txt\n\
        cat build-info/baselogs.txt | sed -n '/^.*Exception in thread/,$p' >> basesummary.txt\n\
        \ncat << EOF > comment-body.txt\n<table>\n<thead>\n<tr>\n<th>Base $(cat build-info/base_sha)</th>\n\
        <th>This Branch $(cat build-info/branch_sha)</th>\n</tr>\n</thead>\n<tr>\n\
        <td>\n\n\\`\\`\\`\n$(cat basesummary.txt)\n\\`\\`\\`\n</td>\n<td>\n\n\\`\\\
        `\\`\n$(cat build-info/branchlogs.txt | sed -n '/^.*Tile stats:/,$p')\n\\\
        `\\`\\`\n</td>\n</tr>\n</table>\n\nhttps://github.com/onthegomap/planetiler/actions/runs/${{\
        \ github.event.workflow_run.id }}\n\n<details><summary>\u2139\uFE0F <strong>Base\
        \ Logs $(cat build-info/base_sha)</strong></summary>\n\n\\`\\`\\`\n$(cat build-info/baselogs.txt)\n\
        \\`\\`\\`\n</details>\n\n<details><summary>\u2139\uFE0F <strong>This Branch\
        \ Logs $(cat build-info/branch_sha)</strong></summary>\n\n\\`\\`\\`\n$(cat\
        \ build-info/branchlogs.txt)\n\\`\\`\\`\n</details>\nEOF\n"
    - continue-on-error: true
      name: Dump comment body
      run: cat comment-body.txt
    - continue-on-error: true
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: performance-tests
        number: ${{ steps.build_info.outputs.pr_number }}
        path: comment-body.txt
    timeout-minutes: 5
name: Update PR
on:
  repository_dispatch:
    types: trigger-ga___update-pr.yml
